version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: classroom_postgres
    environment:
      POSTGRES_DB: classroom_db
      POSTGRES_USER: classroom_user
      POSTGRES_PASSWORD: classroom_pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U classroom_user -d classroom_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:


